# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spisok_coffee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spisok_coffee(object):
    def setupUi(self, spisok_coffee):
        spisok_coffee.setObjectName("spisok_coffee")
        spisok_coffee.resize(800, 651)
        self.centralwidget = QtWidgets.QWidget(spisok_coffee)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 771, 551))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.add_or_change = QtWidgets.QPushButton(self.centralwidget)
        self.add_or_change.setGeometry(QtCore.QRect(10, 560, 171, 41))
        self.add_or_change.setObjectName("add_or_change")
        spisok_coffee.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(spisok_coffee)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        spisok_coffee.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(spisok_coffee)
        self.statusbar.setObjectName("statusbar")
        spisok_coffee.setStatusBar(self.statusbar)

        self.retranslateUi(spisok_coffee)
        QtCore.QMetaObject.connectSlotsByName(spisok_coffee)

    def retranslateUi(self, spisok_coffee):
        _translate = QtCore.QCoreApplication.translate
        spisok_coffee.setWindowTitle(_translate("spisok_coffee", "Список кофе"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("spisok_coffee", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("spisok_coffee", "название сорта"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("spisok_coffee", "Степень обжарки"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("spisok_coffee", "молотый/в зернах"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("spisok_coffee", "Описание вкуса"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("spisok_coffee", "цена"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("spisok_coffee", "объем упаковки"))
        self.add_or_change.setText(_translate("spisok_coffee", "Добавить/Изменить данные"))
